<#
.SYNOPSIS
  Policy promotion pipeline: audit -> staged -> enforce with rollback

.DESCRIPTION
  Manages lifecycle for AppLocker candidate policies generated by tools/self_heal.ps1.
  Tracks state in `policy_state.json`, applies staged policies for a stability window,
  promotes to enforcement when safe, and provides an automated rollback path.
#>

param(
    [Parameter(Mandatory=$false)] [string]$CandidatePath,
    [string]$StateFile = (Join-Path $PSScriptRoot 'policy_state.json'),
    [int]$StabilityMinutes = 60,
    [int]$RequiredCleanCycles = 3,
    [int]$MaxAdd = 20,
    [switch]$DryRun,
    [switch]$CIAdvance,
    [string]$SimulationReport,
    [switch]$StrictParsing
)

Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'AppLocker.PolicyCompiler.psm1') -Force -ErrorAction Stop

function Load-State {
    param($path)
    if (Test-Path $path) { return Get-Content $path -Raw | ConvertFrom-Json }
    return [pscustomobject]@{ stage = 'audit'; candidate = $null; lastGood = $null; stagedAt = $null; cleanCycles = 0 }
}

function Save-State { param($state,$path) $state | ConvertTo-Json -Depth 6 | Set-Content $path }

function NowUtc { (Get-Date).ToUniversalTime() }

function Apply-StagedPolicy {
    param($candidate,$applyPath)
    # Apply the staged candidate as-is. Candidates MUST include baseline rules
    # (injected during IR merge) to be considered valid and self-sufficient.
    $ir = Parse-AppLockerPolicyXml -Path $candidate -ErrorAction Stop
    $requiredBaseline = @('%SystemRoot%\System32\*','%SystemRoot%\*','%ProgramFiles%\*','%ProgramFiles(x86)%\*')
    foreach ($b in $requiredBaseline) {
        $found = $false
        foreach ($r in $ir.Rules) {
            try {
                $rp = $null
                if ($r.PSObject.Properties['Condition']) { $rp = $r.Condition.Path }
                elseif ($r.PSObject.Properties['Path']) { $rp = $r.Path }
                $ra = if ($r.PSObject.Properties['Action']) { $r.Action } else { $null }
                if ($rp -and ($rp -ieq $b) -and ($ra -ieq 'Allow')) { $found = $true; break }
            } catch { }
        }
        if (-not $found) { throw "Candidate missing required baseline allow rule: $b" }
    }
    Copy-Item -Path $candidate -Destination $applyPath -Force
}

function Rollback-ToLastGood {
    param($state,$applyPath)
    if (-not $state.lastGood) { throw 'No lastGood available for rollback' }
    Copy-Item -Path $state.lastGood -Destination $applyPath -Force
}

function Confidence-Score {
    param($diff)
    $addedCount = @($diff.Added).Count
    $score = 100 - ($addedCount * 5)
    if ($score -lt 0) { $score = 0 }
    return $score
}

# Constants / apply target
$applyPolicyPath = Join-Path $PSScriptRoot 'active_policy.xml'

# Baseline representative sample workload (kept conservative)
$baselineSamples = @(
    'C:\Windows\System32\cmd.exe',
    'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe',
    'C:\inetpub\wwwroot\moodle\bin\php.exe'
)

# Always have a sampleFiles collection initialized to avoid undefined variable errors
$sampleFiles = @($baselineSamples)

function Get-SampleFilesFromSimulation {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)][string]$Path,
        [int]$MaxSamples = 25
    )
    if (-not $Path -or -not (Test-Path $Path)) { return @() }
    $lines = Get-Content -Path $Path -ErrorAction SilentlyContinue
    $files = @()
    foreach ($line in $lines) {
        if ($line -match '(?i)\.exe') {
            $token = ($line -split '\s+' | Where-Object { $_ -match '^[a-zA-Z]:\\.*\.exe' } | Select-Object -First 1)
            if ($token) { $files += $token }
        }
    }
    $files = $files | Where-Object { $_ -and ($_ -notmatch '\\Temp\\') -and ($_ -notmatch '\\AppData\\Local\\Temp\\') } | Sort-Object -Unique
    return $files | Select-Object -First $MaxSamples
}

function Parse-SimulationStructured {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [int]$MaxSamples = 25
    )

    if (-not (Test-Path $Path)) { throw "Simulation report not found: $Path" }
    $raw = Get-Content -Path $Path -Raw -ErrorAction Stop
    if (-not $raw -or $raw.Trim().Length -eq 0) { throw "Simulation report is empty" }

    # Normalizer: produce canonical objects with Path, Result, Type
    function Normalize-Event($n) {
        $p = $null; $r = $null; $t = $null

        # Path aliases
        if ($null -ne ($n | Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue)) { $p = $n.Path }
        elseif ($null -ne ($n | Select-Object -ExpandProperty File -ErrorAction SilentlyContinue)) { $p = $n.File }
        elseif ($null -ne ($n | Select-Object -ExpandProperty FilePath -ErrorAction SilentlyContinue)) { $p = $n.FilePath }
        elseif ($null -ne ($n | Select-Object -ExpandProperty filepath -ErrorAction SilentlyContinue)) { $p = $n.filepath }

        # Result aliases
        if ($null -ne ($n | Select-Object -ExpandProperty Result -ErrorAction SilentlyContinue)) { $r = $n.Result }
        elseif ($null -ne ($n | Select-Object -ExpandProperty Decision -ErrorAction SilentlyContinue)) { $r = $n.Decision }
        elseif ($null -ne ($n | Select-Object -ExpandProperty Status -ErrorAction SilentlyContinue)) { $r = $n.Status }

        # Type alias
        if ($null -ne ($n | Select-Object -ExpandProperty Type -ErrorAction SilentlyContinue)) { $t = $n.Type }
        elseif ($null -ne ($n | Select-Object -ExpandProperty Kind -ErrorAction SilentlyContinue)) { $t = $n.Kind }

        if (-not $t) { $t = 'Exe' }

        # Normalize result to canonical 'Allow' or 'Deny' where possible
        if ($r) {
            switch -Regex ($r.ToString()) {
                '^(?i)(allow|allowed|true|yes)$' { $r = 'Allow'; break }
                '^(?i)(deny|denied|false|no|blocked)$' { $r = 'Deny'; break }
                default { $r = $r.ToString() }
            }
        }

        return [pscustomobject]@{ Path = $p; Result = $r; Type = $t }
    }

    $rawCandidates = @()

    # Try JSON
    try {
        $json = $raw | ConvertFrom-Json -ErrorAction Stop
        if ($json) {
            $nodes = $null
            if ($json.events) { $nodes = $json.events } elseif ($json.entries) { $nodes = $json.entries } else { $nodes = $json }
            if ($nodes) { $rawCandidates += ,@($nodes) }
        }
    } catch {}

    # Try XML
    try {
        [xml]$xml = $raw
        if ($xml) {
            $nodes = $xml.SelectNodes('//Event')
            if (-not $nodes) { $nodes = $xml.SelectNodes('//entry') }
            if ($nodes) { $rawCandidates += ,@($nodes) }
        }
    } catch {}

    # Try key-value lines
    $lines = $raw -split "`n"
    $kv = @()
    foreach ($line in $lines) {
        if ($line -match 'RESULT=(?<r>[^;]+);.*PATH=(?<p>[A-Za-z]:\\[^;]+);.*TYPE=(?<t>[^;]+)') {
            $kv += [pscustomobject]@{ Path = $Matches.p; Result = $Matches.r; Type = $Matches.t }
        } elseif ($line -match 'PATH=(?<p>[A-Za-z]:\\[^;]+);.*RESULT=(?<r>[^;]+);.*TYPE=(?<t>[^;]+)') {
            $kv += [pscustomobject]@{ Path = $Matches.p; Result = $Matches.r; Type = $Matches.t }
        }
    }
    if ($kv.Count -gt 0) { $rawCandidates += ,@($kv) }

    # Flatten and normalize candidates
    $flatten = @()
    foreach ($c in $rawCandidates) {
        foreach ($n in $c) { $flatten += (Normalize-Event $n) }
    }

    # Validate and filter — require Path and Result
    $events = $flatten | Where-Object { $_.Path -and $_.Result } | ForEach-Object {
        # ensure Path is trimmed and normalized
        $_.Path = $_.Path.ToString().Trim()
        $_.Result = $_.Result.ToString().Trim()
        $_.Type = $_.Type.ToString().Trim()
        $_
    }

    if ($events.Count -gt 0) { Write-Verbose "Parsed simulation with $($events.Count) validated events" ; return $events | Select-Object -First $MaxSamples }

    throw "Structured parse failed: unsupported simulation format or missing Path/Result"
}

function Run-SimSamples {
    param(
        $PolicyObj,
        [array]$Files
    )
    function Normalize-SimResult {
        param($r)
        $path = $null
        if ($null -ne ($r | Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue)) { $path = $r.Path }
        elseif ($null -ne ($r | Select-Object -ExpandProperty File -ErrorAction SilentlyContinue)) { $path = $r.File }
        elseif ($null -ne ($r | Select-Object -ExpandProperty FilePath -ErrorAction SilentlyContinue)) { $path = $r.FilePath }
        elseif ($r -is [string]) { $path = $r }

        $result = $null
        if ($null -ne ($r | Select-Object -ExpandProperty Result -ErrorAction SilentlyContinue)) { $result = $r.Result }
        elseif ($null -ne ($r | Select-Object -ExpandProperty Decision -ErrorAction SilentlyContinue)) { $result = $r.Decision }
        if (-not $result) { $result = 'Unknown' }

        # Safely extract Error property (works for PSCustomObject, hashtable, strings)
        $errVal = $null
        try { $errVal = ($r | Select-Object -ExpandProperty Error -ErrorAction SilentlyContinue) } catch { $errVal = $null }
        if (-not $errVal -and ($r -is [System.Collections.Hashtable])) {
            if ($r.ContainsKey('Error')) { $errVal = $r['Error'] }
            elseif ($r.ContainsKey('error')) { $errVal = $r['error'] }
        }

        return [pscustomobject]@{ File = $path; Result = $result; Error = $errVal; Raw = $r }
    }

    $results = @()
    foreach ($f in $Files) {
        try {
            $res = Simulate-Execution -PolicyRules $PolicyObj -Type 'Exe' -FilePath $f -ErrorAction Stop
            $norm = Normalize-SimResult $res
            if (-not $norm.File) { $norm.File = $f }
            $allowed = $false
            if ($norm.Result -and ($norm.Result -eq 'Allow')) { $allowed = $true }
            $results += [pscustomobject]@{ File = $norm.File; Allowed = $allowed; Raw = $norm.Raw; Error = $norm.Error }
        } catch {
            $results += [pscustomobject]@{ File = $f; Allowed = $false; Error = $_.Exception.Message }
        }
    }
    return $results
}

$state = Load-State $StateFile

Write-Output "Current stage: $($state.stage)"

switch ($state.stage) {
    'audit' {
        Write-Output 'Promoting candidate into staged state'
        # Allow invocation without CandidatePath if state already has one recorded
        if (-not $CandidatePath -and $state.candidate) {
            $CandidatePath = $state.candidate
            Write-Output "Using existing candidate from state: $CandidatePath"
        }
        if (-not $CandidatePath) { throw 'No candidate provided to stage' }

        # If strict parsing requested, validate the simulation report first to avoid staging on unstructured logs
        if ($StrictParsing -and $SimulationReport) {
            try {
                Write-Output 'StrictParsing: validating simulation report before staging'
                $tmp = Parse-SimulationStructured -Path $SimulationReport -MaxSamples 1
                if (-not $tmp -or $tmp.Count -eq 0) { throw 'Structured parser returned no events' }
            } catch {
                Write-Output "StrictParsing validation failed: $($_.Exception.Message)"; exit 1
            }
        }

        $state.stage = 'staged'
        $state.candidate = $CandidatePath
        $state.stagedAt = (NowUtc).ToString('o')
        $state.cleanCycles = 0
        Save-State $state $StateFile
        Write-Output "Staged: $CandidatePath at $($state.stagedAt)"
        exit 0
    }

    'staged' {
        Write-Output 'Evaluating staged policy'
        if (-not $state.candidate) { throw 'No candidate recorded in state' }

        # Re-parse original active policy and candidate
        if (-not (Test-Path $state.candidate)) { throw 'Candidate file missing' }
        $oldIR = Parse-AppLockerPolicyXml -Path $applyPolicyPath -ErrorAction SilentlyContinue
        $newIR = Parse-AppLockerPolicyXml -Path $state.candidate -ErrorAction Stop

        $diff = Compare-AppLockerIR -Left $oldIR -Right $newIR
        $addedCount = @($diff.Added).Count
        $removedCount = @($diff.Removed).Count
        $changedCount = @($diff.Changed).Count
        Write-Output "Diff: Added=$addedCount Removed=$removedCount Changed=$changedCount"

        $confidence = Confidence-Score -diff $diff
        Write-Output "Confidence score: $confidence"
        if ($confidence -lt 70) { Write-Output 'Low confidence; abort promotion' ; exit 1 }

        # Simulate candidate (best-effort) unless CIAdvance is enabled
                if ($CIAdvance) {
                    Write-Output 'CIAdvance active: skipping real simulation checks'
                } else {
                    if (Get-Command Simulate-Execution -ErrorAction SilentlyContinue) {
                        Write-Output 'Running simulation on candidate (multi-sample)'
                        try {
                            # Merge baseline and dynamic samples (dynamic from simulation report if provided)
                            $dynamic = @()
                            if ($SimulationReport) {
                                if ($StrictParsing) {
                                    Write-Output 'StrictParsing enabled: using structured parser for simulation report'
                                    $events = Parse-SimulationStructured -Path $SimulationReport -MaxSamples 25
                                    $dynamic = $events | Where-Object { (($_.PSObject.Properties['Type'] -and ($_.Type -match 'Exe')) -or ($_.PSObject.Properties['Path'] -and ($_.Path -match '\.exe$'))) } | ForEach-Object { $_.Path }
                                } else {
                                    $dynamic = Get-SampleFilesFromSimulation -Path $SimulationReport -MaxSamples 25
                                }
                            }
                            # If strict parsing and we have validated events, use the event paths as the authoritative sample set.
                            if ($StrictParsing -and $events -and $events.Count -gt 0) {
                                $sampleFiles = $events | ForEach-Object { $_.Path } | Where-Object { $_ } | Sort-Object -Unique
                            } else {
                                $sampleFiles = @($baselineSamples + $dynamic) | Sort-Object -Unique
                            }
                            # persist parsed events and sample list for debugging/CI
                            try {
                                $outDir = Join-Path $PSScriptRoot 'runs'
                                if (-not (Test-Path $outDir)) { New-Item -Path $outDir -ItemType Directory | Out-Null }
                                $ts = (Get-Date).ToString('yyyyMMdd_HHmmss')
                                    if ($StrictParsing -and $events) {
                                        $events | ConvertTo-Json -Depth 6 | Out-File (Join-Path $outDir "parsed_events_$ts.json") -Encoding utf8
                                        $sampleFiles | ConvertTo-Json -Depth 3 | Out-File (Join-Path $outDir "samples_$ts.json") -Encoding utf8
                                        Write-Output "Wrote parsed events and samples to runs/parsed_events_$ts.json and runs/samples_$ts.json"
                                    }
                            } catch { Write-Output "Failed to persist parsed artifacts: $($_.Exception.Message)" }
                            Write-Output "Using sample set: $($sampleFiles -join ', ')"
                            # Create a simulation-only rules array (clone rules).
                            # Baseline allow rules must be present in the candidate IR (merged at IR build time).
                            $simRules = @()
                            foreach ($r in $newIR.Rules) { $simRules += $r }
                            $simResults = Run-SimSamples -PolicyObj $simRules -Files $sampleFiles
                            $denied = $simResults | Where-Object { -not $_.Allowed }
                                                if ($denied.Count -gt 0) {
                                                    Write-Output "Simulation denied for the following sample(s):"
                                                    $denied | ForEach-Object {
                                                        $err = $null
                                                        try {
                                                            if ($_.PSObject.Properties.Match('Error').Count -gt 0) { $err = $_.PSObject.Properties['Error'].Value }
                                                            elseif ($_.PSObject.Properties.Match('Raw').Count -gt 0 -and $_.Raw) {
                                                                try { $err = $_.Raw.Result } catch { $err = $_.Raw }
                                                            }
                                                        } catch { $err = $null }
                                                        if (-not $err) { $err = 'Denied' }
                                                        Write-Output " - $($_.File) : $err"
                                                    }
                                $state.cleanCycles = 0
                                Save-State $state $StateFile
                                exit 1
                            }
                        } catch {
                            Write-Output "Simulation failed: $($_.Exception.Message)"
                            $state.cleanCycles = 0
                            Save-State $state $StateFile
                            exit 1
                        }
                    } else {
                        Write-Output 'No Simulate-Execution available; relying on diff checks only'
                    }
                }

        # Time-based stability: only promote after staged has been clean for required cycles
        if (-not $CIAdvance) {
            $stagedAt = [datetime]::Parse($state.stagedAt)
            $elapsed = (NowUtc) - $stagedAt
            if ($elapsed.TotalMinutes -lt $StabilityMinutes) {
                Write-Output "Staged less than stability window ($StabilityMinutes minutes). Waiting."
                exit 0
            }
            # Record clean cycle and promote if enough cycles have passed
            $state.cleanCycles = ($state.cleanCycles + 1)
            Save-State $state $StateFile
            if ($state.cleanCycles -lt $RequiredCleanCycles) { Write-Output "Clean cycles: $($state.cleanCycles)/$RequiredCleanCycles — wait more" ; exit 0 }
        } else {
            # CI advance: increment cleanCycles immediately for testing
            $state.cleanCycles = ($state.cleanCycles + 1)
            Save-State $state $StateFile
            Write-Output "CIAdvance: incremented cleanCycles to $($state.cleanCycles) (required $RequiredCleanCycles)"
            if ($state.cleanCycles -lt $RequiredCleanCycles) { Write-Output "CIAdvance: waiting for more cycles" ; exit 0 }
            # if we've reached required cycles, continue to promote (skip elapsed gate)
        }

        Write-Output 'Promoting staged policy to ENFORCE'
        if (-not $DryRun) { Apply-StagedPolicy -candidate $state.candidate -applyPath $applyPolicyPath }
        $state.stage = 'enforce'
        $state.lastGood = $state.candidate
        Save-State $state $StateFile
        Write-Output 'Promotion complete'
        exit 0
    }

    'enforce' {
        Write-Output 'Policy is in enforce mode — monitoring for regressions'
        # Run a monitoring check; if detects denies beyond threshold, rollback
        if (-not $state.lastGood) { Write-Output 'No lastGood recorded' ; exit 1 }
        if (Get-Command Simulate-Execution -ErrorAction SilentlyContinue) {
            Write-Output 'Running monitoring simulation on applied policy'
                try {
                    $appliedIR = Parse-AppLockerPolicyXml -Path $applyPolicyPath -ErrorAction Stop
                    # determine sampleFiles here (merge baseline + dynamic from simulation report)
                    $dynamic = @()
                    if ($SimulationReport) {
                        if ($StrictParsing) {
                            Write-Output 'StrictParsing enabled: using structured parser for simulation report'
                            $events = Parse-SimulationStructured -Path $SimulationReport -MaxSamples 25
                            $dynamic = $events | Where-Object { (($_.PSObject.Properties['Type'] -and ($_.Type -match 'Exe')) -or ($_.PSObject.Properties['Path'] -and ($_.Path -match '\.exe$'))) } | ForEach-Object { $_.Path }
                        } else {
                            $dynamic = Get-SampleFilesFromSimulation -Path $SimulationReport -MaxSamples 25
                        }
                    }
                            # If strict parsing and we have validated events, use the event paths as the authoritative sample set for monitoring.
                            if ($StrictParsing -and $events -and $events.Count -gt 0) {
                                $sampleFiles = $events | ForEach-Object { $_.Path } | Where-Object { $_ } | Sort-Object -Unique
                            } else {
                                $sampleFiles = @($baselineSamples + $dynamic) | Where-Object { $_ } | Sort-Object -Unique
                            }
                    Write-Output "Using sample set for enforce monitoring: $($sampleFiles -join ', ')"
                    # persist parsed events and sample list for debugging/CI
                    try {
                        $outDir = Join-Path $PSScriptRoot 'runs'
                        if (-not (Test-Path $outDir)) { New-Item -Path $outDir -ItemType Directory | Out-Null }
                        $ts = (Get-Date).ToString('yyyyMMdd_HHmmss')
                        if ($StrictParsing -and $events) {
                            $events | ConvertTo-Json -Depth 6 | Out-File (Join-Path $outDir "parsed_events_monitor_$ts.json") -Encoding utf8
                            $sampleFiles | ConvertTo-Json -Depth 3 | Out-File (Join-Path $outDir "samples_monitor_$ts.json") -Encoding utf8
                            Write-Output "Wrote parsed monitor events and samples to runs/parsed_events_monitor_$ts.json and runs/samples_monitor_$ts.json"
                        }
                    } catch { Write-Output "Failed to persist monitoring parsed artifacts: $($_.Exception.Message)" }
                    # Use the applied IR rules as-is for monitoring simulation. Candidate should include baseline.
                    $simAppliedRules = @()
                    foreach ($r in $appliedIR.Rules) { $simAppliedRules += $r }
                    $simResults = Run-SimSamples -PolicyObj $simAppliedRules -Files $sampleFiles
                    $denied = $simResults | Where-Object { -not $_.Allowed }
                    if ($denied.Count -gt 0) {
                        Write-Output "Detected denied sample(s) in enforce — rolling back"
                        $denied | ForEach-Object {
                            $err = $null
                            if ($_.PSObject.Properties['Error']) { $err = $_.Error }
                            elseif ($_.PSObject.Properties['Raw'] -and $_.Raw) {
                                try { $err = $_.Raw.Result } catch { $err = $null }
                            }
                            if (-not $err) { $err = 'Denied' }
                            Write-Output " - $($_.File) : $err"
                        }
                        Rollback-ToLastGood -state $state -applyPath $applyPolicyPath
                        $state.stage = 'audit'
                        Save-State $state $StateFile
                        exit 0
                    }
                } catch {
                    Write-Output "Monitoring simulation failed: $($_.Exception.Message)"
                }
        } else {
            Write-Output 'No simulation available; manual monitoring required'
        }
        exit 0
    }

    Default {
        throw "Unknown state: $($state.stage)"
    }
}
